base: 'https://typo3-todo-list.ddev.site/'
dependencies:
  - kmi/typo3-sitepackage
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    locale: en_US.UTF-8
    navigationTitle: English
    flag: us
rootPageId: 1
websiteTitle: 'TYPO3 ToDo List'
